<div data-bind="scope: 'dmelnyk-frontend-component'">
    <h2 data-bind="text: title"></h2>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "dmelnyk-frontend-component": {
                    "component": "Dmelnyk_UiComponent/js/frontend-component",
                    "title": "<?php echo $block->getTitle(); ?>"
                }
            }
        }
    }
}
</script>
