<?php /** @var $cmsPageViewModel \Dmelnyk\UiComponent\ViewModel\GetCmsPageList */ ?>
<?php $cmsPageViewModel = $block->getData('cmsPageList') ?>
<div data-bind="scope: 'dmelnyk-frontend-component'">
    <h2 data-bind="text: title"></h2>
    <ul>
        <!--ko foreach: {data: getPages(), as 'page'} -->
        <li><a data-bind="attr:{href: page.url}, text: page.title"></a></li>
        <!--/ko-->
    </ul>
    <div data-bind="text: pages"></div>
</div>
<script type="text/x-magento-init">
{
    "*": {
        "Magento_Ui/js/core/app": {
            "components": {
                "dmelnyk-frontend-component": {
                    "component": "Dmelnyk_UiComponent/js/frontend-component",
                    "title": "<?php echo $cmsPageViewModel->getTitle(); ?>",
                    "pages": <?php echo $cmsPageViewModel->getCmsPagesJson(); ?>
                }
            }
        }
    }
}
</script>
